# Base image
FROM node:19.6.1-alpine

# Crea el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios a la imagen
COPY package*.json ./
COPY ./src ./src
COPY ./angular*.json ./
COPY ./tsconfig*.json ./
COPY ./node_modules ./node_modules

# Instala las dependencias y el Angular CLI
RUN npm install -g @angular/cli

# Arranca la aplicación
CMD ["npm", "start"]
